[project]
name = "agiagentic-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "fastapi[standard]>=0.122.0",
  "langchain>=1.1.0",
  "langchain-mcp-adapters>=0.1.14",
]
